#include <iostream>

#define LUD_SLURPER_IMPLEMENTATION
#include <lud_slurper.hpp>


int main(int argc, char* const* argv)
{
	if (argc < 3)
	{
		std::cout << "Usage: " << argv[0] << "path/to/shader.spv name [path/to/outfile.cpp]\n";
		return 0;
	}
	Lud::Slurper reader;
	if (!reader.Open(argv[1], std::ios::in | std::ios::binary | std::ios::ate))
	{
		std::cout << "File: " << argv[1] << " does not exists!";
		return 0;
	}

	std::vector<uint32_t> data = reader.ReadTo<uint32_t>();

	const std::string_view outfile = argc > 3 ? argv[3] : "out.cpp";

	Lud::Slurper writer(outfile, std::ios::out);

	writer
		.WriteLine("// File generated by spvToEmbed.cpp")
		.WriteLine("#include <array>")
		.WriteFmt("static const std::array<uint32_t, {0}> {1} = {{", data.size(), argv[2])
		.SetTabLevel(1)
		.WriteListFmt<uint32_t>(data, "0x{:08X}", ", ", 11)
		.SetTabLevel(0);
	writer.Write("\n};");

	return 0;
}