#ifndef FILEMANAGER_CONFIG_HEADER
#define FILEMANAGER_CONFIG_HEADER

#ifndef FILEMANAGER_NAMESPACE
#define FILEMANAGER_NAMESPACE Fman

#endif // !FILEMANAGER_NAMESPACE

#endif // !FILEMANAGER_CONFIG_HEADER
